name: ci workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
   
env:
  GAR_REPO : ${{ secrets.GAR_REPO }}
  IMAGE_NAME : ${{ secrets.IMAGE_NAME }}
  TAG : ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest


    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          
      - name: "Install dependencies"
        run: go get .
      
      - name: "Run go test"
        run: go test -v ./...

      - name: "Run Go Vet"
        run: go vet ./...

      - id: "auth"
        uses: google-github-actions/auth@v1
        with:
          credentials_json : ${{ secrets.GCP_SA_KEY }}            
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
          
      - name: 'Use gcloud CLI'
        run: |
          'gcloud info'
          'gcloud auth configure-docker asia-south1-docker.pkg.dev'

      - name: "build and push"
        uses: docker/build-push-action@v5
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        with:
          context: .
          push: true
          tags: ${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=registry,ref=${{ env.GAR_REPO }}/${{ env.IMAGE_NAME }}:latest,mode=max
      
      - name: Update Kubernetes manifests
        run: |
          git clone https://jay-bhogayata:${{ secrets.PAT }}@github.com/jay-bhogayata/deployment-stuff.git
          cd deployment-stuff
          git remote set-url origin https://jay-bhogayata:${{ secrets.PAT }}@github.com/jay-bhogayata/deployment-stuff.git        
          sed -i "s|image: asia-south1-docker.pkg.dev/mymicroserviceproj/mycontainersstore/notifyhub:.*|image: asia-south1-docker.pkg.dev/mymicroserviceproj/mycontainersstore/notifyhub:${{ env.TAG }}|g" notifyhub/deployment.yaml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update notifyhub image to ${{ env.TAG }}"
          git push origin main